[package]
name = "glace-program-def"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glsl = "6.0"
crevice = "0.8"
thiserror = "1.0"