[package]
name = "glace-derive"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = "1.0.40"
quote = "1.0.7"
proc-macro2 = "1.0.21"